apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: app-second 
  janus-idp.io/tekton: app-second
  backstage.io/kubernetes-id: app-second
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: app-second
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  